[project]
name = "uv-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "iyuri2519", email = "iyuri2519@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
]

[project.scripts]
uv-study = "uv_study:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
